sudo: false

addons:
  apt:
    packages:
      - tidy
      - tcl
      - tk

install: bundle install --without=benchmark

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - ruby-head

matrix:
  include:
    - rvm: rbx-3.62
      env: RBX_RUBY_COMPAT=2.3.1 RBX_VERSION=3.62


notifications:
  email: false
